---
# Vault
vault.transit.key: default

# Elasticsearch
# ES URI is "${elasticsearch.cluster.scheme}://${elasticsearch.cluster.nodes}:${elasticsearch.cluster.port}"
elasticsearch.cluster.scheme: http
elasticsearch.cluster.port: 9200
elasticsearch.cluster.nodes: elasticsearch
elasticsearch.cluster.name: elasticsearch
elasticsearch.index.prefix: gatekeeper

# MariaDB
mysql.host: mysql
mysql.database: gatekeeper
mysql.port: 3306
#spring.jpa.hibernate.ddl-auto: create
spring.jpa.generate-ddl: true
spring.jpa.hibernate.ddl-auto: update

spring.datasource.url: "jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.database}"
